const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('native', {
  getInfo: () => ipcRenderer.invoke('get-info'),
  getSources: () => ipcRenderer.invoke('get-sources'),
  getPeers: () => ipcRenderer.invoke('get-peers'),
  getDisplayInfo: () => ipcRenderer.invoke('get-display-info'),
  getAutoLaunch: () => ipcRenderer.invoke('get-auto-launch'),
  setAutoLaunch: (enabled) => ipcRenderer.invoke('set-auto-launch', enabled),
  getScreenPermission: () => ipcRenderer.invoke('get-screen-permission'),
  openScreenSettings: () => ipcRenderer.invoke('open-screen-settings'),
  resetScreenPermission: () => ipcRenderer.invoke('reset-screen-permission'),
  openDisplaySettings: () => ipcRenderer.invoke('open-display-settings'),
  setCursorHotkeys: (config) => ipcRenderer.invoke('set-cursor-hotkeys', config),
  cursorToNextDisplay: () => ipcRenderer.invoke('cursor-to-next-display'),
  countDisplays: () => ipcRenderer.invoke('count-displays'),
  setModifierTap: (config) => ipcRenderer.invoke('set-modifier-tap', config),
  getTapStatus: () => ipcRenderer.invoke('get-tap-status'),
  checkAccessibility: (prompt) => ipcRenderer.invoke('check-accessibility', prompt),
  openAccessibilitySettings: () => ipcRenderer.invoke('open-accessibility-settings'),
  onTapStatus: (cb) => ipcRenderer.on('tap-status', (_e, status) => cb(status)),
  onInputControl: (cb) => ipcRenderer.on('input-control', (_e, state) => cb(state)),
  setInputControl: (config) => ipcRenderer.invoke('set-input-control', config),
  resolveDisplayBounds: (displayId) => ipcRenderer.invoke('resolve-display-bounds', displayId),
  relaunch: () => ipcRenderer.invoke('relaunch'),
  copyText: (text) => ipcRenderer.invoke('copy-text', text),
  toggleFullscreen: (desired) => ipcRenderer.invoke('toggle-fullscreen', desired),
  setStreaming: (on) => ipcRenderer.invoke('set-streaming', on),
  virtualDisplay: (opts) => ipcRenderer.invoke('virtual-display', opts),
  onVirtualDisplayChanged: (cb) => ipcRenderer.on('virtual-display-changed', (_e, active) => cb(active)),
  onPeersChanged: (cb) => ipcRenderer.on('peers-changed', (_e, peers) => cb(peers)),
  onSenderDiscovered: (cb) => ipcRenderer.on('sender-discovered', (_e, info) => cb(info)),
});
